name: Check formating, linting, tests, and build apk
on:
    push:
      branches: [master]


jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Prepare the app
        run: |
          flutter clean
          flutter pub get
      - name: Formating
        run: flutter format --set-exit-if-changed .
      - name: Analyze
        run: dart analyze --fatal-infos
      - name: Run tests
        run: flutter test test/widget_test.dart --coverage
      - name: Upload coverage to codecov
        run: curl -s https://codecov.io/bash
        shell: bash
      - name: Build apk
        run: flutter build apk
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk